/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface HelloWorldInterface extends utils.Interface {
  functions: {
    "read()": FunctionFragment;
    "write(uint256)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "read" | "write"): FunctionFragment;

  encodeFunctionData(functionFragment: "read", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "write",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(functionFragment: "read", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "write", data: BytesLike): Result;

  events: {
    "MessageChanged(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "MessageChanged"): EventFragment;
}

export interface MessageChangedEventObject {
  setter: string;
}
export type MessageChangedEvent = TypedEvent<
  [string],
  MessageChangedEventObject
>;

export type MessageChangedEventFilter = TypedEventFilter<MessageChangedEvent>;

export interface HelloWorld extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: HelloWorldInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    /**
     * Get the value
     */
    read(overrides?: CallOverrides): Promise<[BigNumber]>;

    /**
     * Set the value
     * @param newValue Value
     */
    write(
      newValue: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  /**
   * Get the value
   */
  read(overrides?: CallOverrides): Promise<BigNumber>;

  /**
   * Set the value
   * @param newValue Value
   */
  write(
    newValue: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    /**
     * Get the value
     */
    read(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Set the value
     * @param newValue Value
     */
    write(
      newValue: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "MessageChanged(address)"(
      setter?: PromiseOrValue<string> | null
    ): MessageChangedEventFilter;
    MessageChanged(
      setter?: PromiseOrValue<string> | null
    ): MessageChangedEventFilter;
  };

  estimateGas: {
    /**
     * Get the value
     */
    read(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Set the value
     * @param newValue Value
     */
    write(
      newValue: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    /**
     * Get the value
     */
    read(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * Set the value
     * @param newValue Value
     */
    write(
      newValue: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
